version: '3.7'
 
services:
  web:
    build: .
    command: gunicorn --bind=0.0.0.0 signbank.wsgi
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./env.dev
    depends_on: 
      - db
  db:
      image: postgres:12.0-alpine
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      environment:
        - POSTGRES_USER=auslan
        - POSTGRES_PASSWORD=auslan
        - POSTGRES_DB=auslan

volumes:
  postgres_data:

